- src/background/utils/DependencyResolver.ts
- src/inpage/Injector.ts
> specific module decorators

- src/background/models/moduleInfo.ts
- src/background/models/versionInfo.ts
- src/background/registries/devRegistry.ts
- src/background/registries/ethRegistry.ts
- src/background/registries/ethRegistryAbi.ts
- src/background/registries/nftContractAbi.ts
- src/background/services/featureService.ts
- src/background/services/globalConfigService.ts
- src/common/helpers.ts
> feat: working with the lastest version of registry

- src/background/registries/ethRegistry.ts
- src/background/services/featureService.ts
[x] Bug fix
DAP-2301
Added missed `metadata` property to `ModuleInfo` and changed respond processing from `contract.getModulesOfListing()`.
Nope
> fix: cannot deploy module to Ethereum registry (DAP-2301)

- src/contentscript/overlay/root/components/Dapplet/index.tsx
- src/contentscript/overlay/root/components/DevModulesList/index.tsx
- src/contentscript/overlay/root/pages/UserSettings/SettingsPage.tsx
> feat:add owner info in dev-mode

- src/background/index.ts
- src/background/registries/ethRegistry.ts
- src/background/services/featureService.ts
- src/common/helpers.ts
- src/contentscript/overlay/root/App.tsx
- src/contentscript/overlay/root/components/Dropdown/dropdown-list.ts
- src/contentscript/overlay/root/components/Dropdown/index.tsx
- src/contentscript/overlay/root/models/dropdown.model.ts
- src/contentscript/overlay/root/pages/Dapplets/index.tsx
- src/popup/pages/dapplets.tsx
> Dap 2185: Listings request for dropdown

- src/background/index.ts
- src/contentscript/core.ts
- src/contentscript/injector.ts
- src/contentscript/proxyFetch.ts
- tsconfig.json
> feat: introduce Core.fetch() function

- .eslintrc.json
- cypress.config.ts
- cypress/e2e/no-available-dapplets.cy.ts
- cypress/support/commands.ts
- cypress/support/e2e.ts
- cypress/tsconfig.json
- cypress/types.d.ts
- package-lock.json
- package.json
- src/common/helpers.ts
- src/contentscript/index.ts
- src/contentscript/overlay/root/components/OverlayToolbar/index.tsx
- src/contentscript/overlay/root/pages/Dapplets/index.tsx
- src/inpage/dappletsProvider.ts
- src/popup/pages/dapplets.tsx
- tsconfig.json
> test: init cypress and add simple test

- src/background/moduleStorages/centralizedModuleStorage.ts
- src/background/moduleStorages/ipfsModuleStorage.ts
- src/background/moduleStorages/siaModuleStorage.ts
- src/background/moduleStorages/swarmModuleStorage.ts
- src/background/services/discordService.ts
> fix: cannot deploy modules to centralized storage

- src/background/index.ts
- src/background/services/connectedAccountService.ts
- src/background/services/overlayService.ts
- src/contentscript/core.ts
- src/contentscript/index.ts
- src/contentscript/injector.ts
- src/contentscript/overlay/root/pages/ConnectedAccount/index.tsx
[ ] Bug fix
[X] New feature
*issue:* 
For test purposes use Demo Dapplet from this branch: https://github.com/dapplets/dapplet-modules/tree/dap-2836
Use in dapplets: https://github.com/dapplets/dapplet-modules/blob/bf6d84f450af5a5beb22eeb96b0303128eb23297/packages/twitter-demo/src/index.ts#L52-L53
> feat: add subscriptions to Core for wallets update and CA update (DAP-2836)

- package-lock.json
- package.json
- src/background/registries/registryAggregator.ts
- src/background/services/connectedAccountService.ts
> Ca increase attached gas

- cypress/e2e/notifications/actions-in-card-notification.cy.ts
- cypress/e2e/notifications/actions-in-floating-notification.cy.ts
- cypress/e2e/notifications/appearance-new-notification.cy.ts
- cypress/e2e/notifications/open-old-notification.cy.ts
- cypress/support/commands.ts
- cypress/types.d.ts
- src/background/index.ts
- src/background/services/notificationService.ts
- src/background/utils/moduleManager.ts
- src/common/models/notification.ts
- src/contentscript/core.ts
- src/contentscript/events/baseEvent.ts
- src/contentscript/events/eventBus.ts
- src/contentscript/index.ts
- src/contentscript/injector.ts
- src/contentscript/overlay/root/components/Notification/index.tsx
- src/contentscript/overlay/root/components/OverlayToolbar/index.tsx
- src/contentscript/overlay/root/pages/Notifications/index.tsx
- src/index.ts
> [DAP-3314] Module Event Bus + Notification Actions

- src/background/index.ts
- src/background/services/connectedAccountService.ts
- src/contentscript/connectedAccounts/connected-accounts.ts
> feat: add functions areConnected() and getNet() in Connected Accounts

- src/background/models/loginConfirmation.ts
- src/background/services/sessionService.ts
- src/background/wallets/near/interface.ts
- src/background/wallets/near/near/index.ts
- src/common/constants.ts
- src/common/types.ts
- src/contentscript/login/login-session.ts
- src/contentscript/near/backgroundKeyStore.ts
- src/contentscript/near/backgroundNear.ts
- src/contentscript/near/index.ts
- src/contentscript/overlay/root/components/SystemPopup/pages/login-session/WalletPairing.tsx
- src/contentscript/overlay/root/components/SystemPopup/pages/login-session/wallets/Near.tsx
> feat: introduce login sessions for NEAR Protocol

- src/contentscript/overlay/root/components/OverlayTab/index.tsx
- src/contentscript/overlay/root/components/OverlayToolbar/index.tsx
> fix: fixed visible tab menus

- src/contentscript/overlay/root/pages/Settings/Settings/Settings.tsx
> fix: fixed error message to invalid value user agent name

- src/contentscript/modules/config-adapter/widgets/avatar-badge/index.ts
- src/contentscript/modules/parser-configs/post/avatarBadge.css
- src/contentscript/modules/parser-configs/profile/avatarBadge.css
> fix: unification avatar-badge widget

- src/contentscript/modules/config-adapter/widgets/button/index.ts
- src/contentscript/modules/parser-configs/post/button.css
- src/contentscript/modules/parser-configs/profile/button.css
fix: combining styles widget button
> fix: fixed naming widget button

- package-lock.json
- src/contentscript/overlay/root/components/Checkbox/Checkbox.module.scss
> fix: centered icon to checkbox

- src/contentscript/modules/config-adapter/widgets/button/index.ts
- src/contentscript/modules/parser-configs/post/button.css
> fix: fixed styles button-widget

- src/contentscript/modules/config-adapter/widgets/avatar-badge/index.ts
- src/contentscript/modules/parser-configs/post/avatarBadge.css
- src/contentscript/modules/parser-configs/profile/avatarBadge.css
> fix: fixed styles badge-avatar

- src/contentscript/overlay/root/components/Checkbox/Checkbox.module.scss
> fix: fixed styles checkbox

- src/contentscript/overlay/root/App.tsx
> fix: commented share button

- src/contentscript/overlay/root/components/OverlayToolbar/OverlayToolbar.module.scss
- src/contentscript/overlay/root/components/OverlayToolbar/index.tsx
> fix: fixed styles notification

- src/contentscript/overlay/root/pages/Dapplets/index.tsx
> fix: return old version downloads pages Dapplets

- src/contentscript/overlay/root/pages/Settings/Settings/Settings.tsx
> fix: fixed rules to input agent name

- src/contentscript/overlay/root/components/OverlayTab/menuWidgets.scss
- src/contentscript/overlay/root/components/OverlayToolbar/OverlayToolbar.module.scss
> Styles fix (DAP-3775)

- package-lock.json
- package.json
- src/contentscript/overlay/root/components/Checkbox/Checkbox.module.scss
- src/contentscript/overlay/root/components/Checkbox/index.tsx
- src/contentscript/overlay/root/pages/Settings/Settings/Settings.module.scss
- src/contentscript/overlay/root/pages/Settings/Settings/Settings.tsx
fix: added dependencies to classnames
fix: commented swarm checkbox
fix: fixed styles checkbox
[ ] Bug fix
*issue:*
> fix: commented swarm gateway

- src/contentscript/overlay/root/components/OverlayToolbar/Notification/index.tsx
- src/contentscript/overlay/root/components/OverlayToolbar/index.tsx
> fix: notifications disappear (DAP-3754)

- src/contentscript/overlay/root/components/OverlayToolbar/Notification/index.tsx
- src/contentscript/overlay/root/components/OverlayToolbar/OverlayToolbar.module.scss
- src/contentscript/overlay/root/components/OverlayToolbar/index.tsx
> Notification counter is not displayed after the page reload (DAP-3792)

- src/background/wallets/ethereum/dapplets.ts
- src/background/wallets/ethereum/metamask.ts
- src/contentscript/overlay/root/components/Profile/HeaderLogIn/index.tsx
- src/contentscript/overlay/root/components/Profile/ModalLogin/index.tsx
> fix: fixed visible icon metamask

- src/background/services/notificationService.ts
- src/common/models/notification.ts
- src/contentscript/overlay/root/components/LinkifyText/index.tsx
- src/contentscript/overlay/root/components/Notification/index.tsx
- src/contentscript/overlay/root/components/OverlayToolbar/Notification/index.tsx
- src/contentscript/overlay/root/components/OverlayToolbar/OverlayToolbar.module.scss
- src/contentscript/overlay/root/components/OverlayToolbar/index.tsx
- src/contentscript/overlay/root/pages/Notifications/index.tsx
> feat: added notification's teaser

- src/contentscript/overlay/root/components/Profile/ModalLogin/index.tsx
> fix: removed visible modal to click 'esc'

- src/contentscript/overlay/root/components/SystemPopup/pages/login-session/LoginConfirmations.tsx
- src/contentscript/overlay/root/components/SystemPopup/pages/login-session/wallets/Near.tsx
> fix: new near session is created always (DAP-3812)

- src/contentscript/overlay/root/App.tsx
- src/contentscript/overlay/root/components/ContentItem/index.tsx
- src/contentscript/overlay/root/components/Dapplet/index.tsx
- src/contentscript/overlay/root/components/OverlayTab/index.tsx
- src/contentscript/overlay/root/components/OverlayTab/styles/OverlayTab.module.scss
- src/contentscript/overlay/root/components/OverlayTab/styles/adaptive.scss
- src/contentscript/overlay/root/components/OverlayTab/styles/menuWidgets.scss
- src/contentscript/overlay/root/components/OverlayTab/types.ts
- src/contentscript/overlay/root/components/OverlayTab/utils.ts
- src/contentscript/overlay/root/components/OverlayToolbar/index.tsx
- src/contentscript/overlay/root/pages/Dapplets/index.tsx
- src/contentscript/overlay/root/pages/Settings/Developer/Developer.tsx
- src/contentscript/overlay/root/pages/Settings/index.tsx
- src/contentscript/overlay/root/pages/UserSettings/index.tsx
> The icon of the just enabled dapplet does not display in the toolbar (DAP-3793)

- src/contentscript/overlay/root/components/CAUserButton/CAUserButton.module.scss
- src/contentscript/overlay/root/components/DropdownAccounts/DropdownAccounts.module.scss
- src/contentscript/overlay/root/pages/ConnectedAccount/ConnectedAccount.module.scss
- src/contentscript/overlay/root/pages/ConnectedAccount/index.tsx
> DAP-3866, DAP-3867

- src/contentscript/overlay/root/components/OverlayTab/OverlayTab.module.scss
- src/contentscript/overlay/root/components/OverlayTab/index.tsx
- src/contentscript/overlay/root/components/OverlayTab/menuWidgets.scss
fix: fixed action menu button home works
[ ] Bug fix
*issue:*
> fix: fixed styles action menu

- src/contentscript/overlay/root/components/Profile/HeaderLogIn/index.tsx
- src/contentscript/overlay/root/components/Profile/ModalLogin/index.tsx
> fix: fixed mocked count wallets to modal login

- src/contentscript/overlay/root/components/SystemPopup/pages/ConnectedAccountsModal/index.tsx
> fix: changed text to modal connected account

- src/contentscript/overlay/root/pages/DappletsInfo/index.tsx
> fix: fixed update dapplet info page

- src/contentscript/overlay/root/components/Profile/HeaderLogIn/HeaderLogIn.module.scss
> fix: fixed incorrectly font color to login

- src/worker/core/index.ts
> feat: add Core.extension.satisfied() method (DAP-4092)

- package-lock.json
- src/contentscript/overlay/root/pages/DappletsInfo/index.tsx
> fix: fixed errors when adding admins

- src/contentscript/overlay/root/pages/Notifications/index.tsx
> fix: changed dispalay notifications page

- src/background/services/sessionService.ts
- src/common/helpers.ts
- src/common/types.ts
- src/contentscript/overlay/root/components/SystemPopup/pages/login-session/ConnectedWallets.tsx
- src/contentscript/overlay/root/components/SystemPopup/pages/login-session/WalletPairing.tsx
- src/contentscript/overlay/root/components/SystemPopup/pages/login-session/index.tsx
- src/contentscript/overlay/root/components/SystemPopup/pages/login-session/wallets/Dapplets.tsx
- src/contentscript/overlay/root/components/SystemPopup/pages/login-session/wallets/MetaMask.tsx
- src/contentscript/overlay/root/components/SystemPopup/pages/login-session/wallets/Near.tsx
- src/contentscript/overlay/root/components/SystemPopup/pages/login-session/wallets/WalletConnect.tsx
- src/worker/core/index.ts
> feat: explicit reuse of login confirmations (DAP-4111)

- src/contentscript/overlay/root/App.tsx
- src/contentscript/overlay/root/components/ContentItem/ContentItem.module.scss
- src/contentscript/overlay/root/components/ContentItem/index.tsx
- src/contentscript/overlay/root/components/OverlayTab/index.tsx
- src/contentscript/overlay/root/components/OverlayTab/styles/OverlayTab.module.scss
- src/contentscript/overlay/root/components/SquaredButton/SquaredButton.module.scss
> fix: changed styles icon user settings

- src/background/index.ts
- src/common/global-event-bus.ts
- src/contentscript/index.ts
- src/popup/App.tsx
- src/popup/components/InfoIcon.tsx
- src/popup/index.html
- src/popup/index.ts
- src/popup/index.tsx
- webpack.common.js
> feat: show popup when content script is not injected

- src/contentscript/overlay/root/components/Overlay/Overlay.module.scss
- src/contentscript/overlay/root/pages/Dapplets/Dapplets.module.scss
- src/contentscript/overlay/root/pages/DappletsInfo/DappletsInfo.module.scss
- src/contentscript/overlay/root/pages/Settings/Developer/Developer.module.scss
- src/contentscript/overlay/root/pages/Settings/Settings/Settings.module.scss
- src/contentscript/overlay/root/pages/UnderConstructionInfo/UnderConstructionInfo.module.scss
> fix: changed container styles

- package-lock.json
- src/contentscript/overlay/root/components/Dapplet/Dapplet.module.scss
> fix: changed styles dapplet's card

- src/contentscript/overlay/root/components/OverlayTab/index.tsx
> fix: fixed error undefined props

- src/contentscript/overlay/root/components/Notification/Notification.module.scss
- src/contentscript/overlay/root/pages/Notifications/index.tsx
> Fixes: notification action button styles, resolved notification are sorted to the list bottom (DAP-4212, DAP-4213)

- package-lock.json
- src/contentscript/overlay/root/components/Profile/ModalLogin/Modal.module.scss
- src/contentscript/overlay/root/components/Profile/ModalLogin/index.tsx
> fix: changed styles wallets' popup

- .vscode/settings.json
- src/contentscript/overlay/root/components/Dapplet/Dapplet.module.scss
- src/contentscript/overlay/root/components/Dapplet/adaptive.scss
- src/contentscript/overlay/root/components/Dapplet/index.tsx
- src/contentscript/overlay/root/components/DappletTitle/DappletTitle.module.scss
- src/contentscript/overlay/root/components/DappletTitle/index.tsx
- src/contentscript/overlay/root/components/DevModulesList/DevModulesList.module.scss
- src/contentscript/overlay/root/components/Overlay/Overlay.module.scss
- src/contentscript/overlay/root/components/Switch/Switch.module.scss
- src/contentscript/overlay/root/pages/DappletsInfo/DappletsInfo.module.scss
- src/contentscript/overlay/root/pages/DappletsInfo/index.tsx
- src/contentscript/overlay/root/pages/Notifications/Notifications.module.scss
- src/contentscript/overlay/root/pages/Settings/Developer/Developer.module.scss
- src/contentscript/overlay/root/pages/Settings/index.tsx
- src/contentscript/overlay/root/pages/UnderConstructionInfo/index.tsx
> fix: changed styles

- src/contentscript/overlay/root/assets/icons/closeLocalhost.svg
- src/contentscript/overlay/root/components/Localhost/Localhost.module.scss
- src/contentscript/overlay/root/components/Localhost/index.tsx
- src/contentscript/overlay/root/components/Registry/Registry.module.scss
- src/contentscript/overlay/root/components/SettingTitle/SettingTitle.module.scss
> fix: changed styles developer page

- src/contentscript/overlay/root/components/SettingItem/SettingItem.module.scss
- src/contentscript/overlay/root/components/SettingTitle/SettingTitle.module.scss
- src/contentscript/overlay/root/components/SettingWrapper/SettingWrapper.module.scss
- src/contentscript/overlay/root/pages/Settings/Settings/Settings.module.scss
- src/contentscript/overlay/root/pages/Settings/Settings/Settings.tsx
> fix: changed styles settings page
